= 1) RestDocs API
:doctype: book
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:seclinks:

== link:index.html[Back to Index, window=blank]

== APIs

// 추가할 snippets 양식
// operation::{Test Controller 명 - Kebab Case}/{Test Method 명 - Kebab Case}/[snippets="사용할 snippets"]

[[Get]]
=== 1. Get Object
==== : 단건 조회 API

=====
operation::rest-docs-controller-test/get-rest-docs-test/[snippets="path-parameters,response-fields,http-response"]
=====

'''

[[Get-With-Headers]]
=== 1-1. Get Object with Headers
==== : 단건 조회 API (With Headers)

=====
operation::rest-docs-controller-test/get-rest-docs-with-headers-test/[snippets="path-parameters,request-headers,response-fields,http-response"]
=====

'''

[[List]]
=== 2. List Objects
==== : 다건 조회 API

=====
operation::rest-docs-controller-test/list-rest-docs-test/[snippets="query-parameters,response-fields,http-response"]
=====

'''

[[Create]]
=== 3. Create Object
==== : 생성 API

=====
operation::rest-docs-controller-test/post-rest-docs-test/[snippets="request-body,request-fields,response-fields,http-response"]
=====

'''

[[Update]]
=== 4. Update Object
==== : 수정 API

=====
operation::rest-docs-controller-test/put-rest-docs-test/[snippets="path-parameters,request-fields,request-body,response-fields,http-response"]
=====

'''

[[Delete]]
=== 5. Delete Object
==== : 삭제 API

=====
operation::rest-docs-controller-test/delete-rest-docs-test/[snippets="path-parameters,http-response"]
=====