= 1) RestDocs API
:doctype: book
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:seclinks:

== link:index.html[Back to Index, window=blank]

== APIs

[[Get]]
=== 1. Get RestDocs
==== : 단건 조회 API


=====
operation::rest-docs-controller-test/get-rest-docs-test/[snippets="curl-request,path-parameters,response-body,response-fields,http-response"]
=====

'''

[[List]]
=== 2. List RestDocs
==== : 다건 조회 API

=====
operation::rest-docs-controller-test/list-rest-docs-test/[snippets="curl-request,query-parameters,response-body,response-fields,http-response"]
=====

'''

[[Create]]
=== 3. Create RestDocs
==== 생성 API

=====
operation::rest-docs-controller-test/post-rest-docs-test/[snippets="curl-request,request-body,request-fields,response-body,response-fields,http-response"]
=====

'''

[[Update]]
=== 4. Update RestDocs
==== 수정 API

=====
operation::rest-docs-controller-test/put-rest-docs-test/[snippets="curl-request,path-parameters,request-body,response-body,response-fields,http-response"]
=====

'''

[[Delete]]
=== 5. Delete RestDocs
==== 삭제 API

=====
operation::rest-docs-controller-test/delete-rest-docs-test/[snippets="curl-request,path-parameters,http-response"]
=====