name: deerear_cd
on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Build application
      run: |
        chmod +x ./gradlew
        ./gradlew build
    
    - name: Docker hub login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker image build
      run: |
        docker build -t ${{secrets.DOCKERHUB_USERNAME}}/deerear .

    - name: Docker Hub push
      run: docker push ${{secrets.DOCKERHUB_USERNAME}}/deerear

    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        timeout: '30s'
        script: |
          bash ${{secrets.DEPLOY_SCRIPT}}