name: deerear_ci
on:
  pull_request:
    branches: ["develop"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build application
      env:
        JWT_SECRET_KEY: ${{secrets.JWT_SECRET_KEY}}
        SPRING_DATASOURCE_URL: ${{secrets.SPRING_DATASOURCE_URL}}
        SPRING_DATASOURCE_USERNAME: ${{secrets.SPRING_DATASOURCE_USERNAME}}
        SPRING_DATASOURCE_PASSWORD: ${{secrets.SPRING_DATASOURCE_PASSWORD}}
      run: |
        chmod +x ./gradlew
        ./gradlew clean
        ./gradlew --info test

